package com.sunny.permission.entry;

public class SysRolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.sys_role_id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    private String sys_role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.sys_permission_id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    private String sys_permission_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.id
     *
     * @return the value of sys_role_permission.id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.id
     *
     * @param id the value for sys_role_permission.id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.sys_role_id
     *
     * @return the value of sys_role_permission.sys_role_id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    public String getSys_role_id() {
        return sys_role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.sys_role_id
     *
     * @param sys_role_id the value for sys_role_permission.sys_role_id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    public void setSys_role_id(String sys_role_id) {
        this.sys_role_id = sys_role_id == null ? null : sys_role_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.sys_permission_id
     *
     * @return the value of sys_role_permission.sys_permission_id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    public String getSys_permission_id() {
        return sys_permission_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.sys_permission_id
     *
     * @param sys_permission_id the value for sys_role_permission.sys_permission_id
     *
     * @mbg.generated Fri Dec 07 14:10:43 GMT+08:00 2018
     */
    public void setSys_permission_id(String sys_permission_id) {
        this.sys_permission_id = sys_permission_id == null ? null : sys_permission_id.trim();
    }
}